name: test
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  
jobs: 

 build:
    permissions: write-all
    needs: check
    uses: ./.github/workflows/build.yml
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
    secrets: inherit
  
